install:
- curl -sLo metaeditor.exe https://github.com/EA31337/FX-MT-VM/releases/download/4.x/metaeditor.exe
- git clone -q --recursive https://github.com/EA31337/EA31337-classes ../include/EA31337-classes
before_test:
#- mklink /D "..\include\EA31337-classes" "%cd%"
- pwd
clone_script:
- git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- git checkout -qf %APPVEYOR_REPO_COMMIT%
test_script:
- metaeditor /s /compile:. /inc:.. /log:errors.log || exit /b 0
- type *.log
- type *.log | find /v "Result" | findstr "error" && exit /b 1 || exit /b 0
- type *.log | find /v "Result" | findstr "warning" && exit /b 1 || exit /b 0
build: off
platform: x86
